# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 538c9e61245fa2aacd3419214fbf275fed410480b9581f0a3527fe2f99cc7c5cd5f0116bc5a1e9cb5a11baeb72cad6c2befc352feb8e4aee005d84dc2873827c

test:
  secret_key_base: 38db541deebd8cdaeeab822cd9a2ab918f054063e763b889441d70c22cf69d0b71b6dc19cd46d7798b45086ff7c8ae10433ad854f240cbb69e271db75287346e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
